baseURL                          = "https://samchorlton.com/"  # Your domain name. Must end with "/"
theme                            = "introduction"
title 				 = "Sam Chorlton"
#DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
googleAnalytics                 = "UA-129345906-1"                       # https://gohugo.io/templates/internal/#google-analytics
enableRobotsTXT = true
canonifyURLs = true

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "favicon.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = ""   # E-mail address for contact section
    customCSS                    = ["custom.css"]             # Include custom css files placed under assets/
	author = "Sam Chorlton"
	description = "Sam Chorlton's Site"
	

    # Configure the home page
    [params.home]
        introHeight              = "medium"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three



[blackfriday] hrefTargetBlank = true


[[menu.main]]
  name = "Publications"
  url = "#publications"
weight = 1  

[[menu.main]]
  name = "Presentations"
  url = "#presentations"
weight = 2

[[menu.main]]
  name = "Educational Material"
  url = "#educational"
weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
weight = 5

[[menu.main]]
    name = "Github"
  
    url = "https://github.com/schorlton"
	weight = 4
